### ISSUE TITLE
Form.BackColor seems not work

### ISSUE THREAD

**Issue by erisonliang** [samuelGrahame/ExpressCraft#34]
Hi, I tried to set Form.BackColor = "yellow". But it still show in White color.  Could you please let me know how to configure Form's BackColor correctly. Thanks.

**Comment by samuelGrahame** [comment]
Hey I have fixed the issue, There was a css rule that was overriding that color.

above will would if you sync on github

**Comment by samuelGrahame** [comment]
Nuget package has been released with this fix.
ver: 0.5.6
